import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import cssModulesPlugin from "esbuild-css-modules-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/closebrackets",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/comment",
			"@codemirror/fold",
			"@codemirror/gutter",
			"@codemirror/highlight",
			"@codemirror/history",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/matchbrackets",
			"@codemirror/panel",
			"@codemirror/rangeset",
			"@codemirror/rectangular-selection",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/stream-parser",
			"@codemirror/text",
			"@codemirror/tooltip",
			"@codemirror/view",
			...builtins,
		],
		format: "cjs",
		watch: !prod,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		entryNames: "[name]", // Use the entry name as the output name
		plugins: [
			cssModulesPlugin({
				inject: false, // Do not inject CSS into JS
				outdir: "obsidian-dev-vault/.obsidian/plugins/Full-Calender", // Output directory for CSS
				outbase: "src", // Base directory for CSS output
				rename: {
					"main.css": "styles.css", // Rename the output CSS file
				},
			}),
		],

		outfile: "obsidian-dev-vault/.obsidian/plugins/Full-Calender/main.js",
	})
	.catch(() => process.exit(1));
