import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function build() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    target: "es2016",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    entryNames: "[name]", // Use the entry name as the output name
    plugins: [
      {
        name: 'rename-css-plugin',
        setup(build) {
          build.onEnd(() => {

            const cssOutputDir = "obsidian-dev-vault/.obsidian/plugins/Full-Calender";
            const oldPath = path.join(cssOutputDir, "main.css");
            const newPath = path.join(cssOutputDir, "styles.css");

            if (fs.existsSync(oldPath)) {
              fs.renameSync(oldPath, newPath);
              console.log(" | Renamed CSS to styles.css");
            } else {
              console.warn("⚠️ CSS file not found to rename");
            }
          });
        }
      }
    ],
    outfile: "obsidian-dev-vault/.obsidian/plugins/Full-Calender/main.js",
  });

  if (!prod) {
    context.watch();
    console.log('Watching for changes...');
  } else {
    await context.rebuild();
    context.dispose();
  }
}

build().catch(() => process.exit(1));
